### ISSUE TITLE
Error extracting SVG created with an AngularJS directive (Support for more CSS rules)

### ISSUE THREAD

**Issue by lobo-tuerto** [exupero/saveSvgAsPng#11]
I just got the file from the master branch and I'm seeing this error:

```
Error: Failed to execute 'querySelectorAll' on 'Element': '[ng:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak, .ng-hide:not(.ng-animate)' is not a valid selector.
```

Tried this on a svg generated through a directive in angular (in case you were wondering about where does those names come from).

Invoking line:

```
saveSvgAsPng(document.getElementById("diagram"), "diagram.png", 3);
```

**Comment by prabhatsingh-db** [comment]
I am also facing the same issue.getting below error in chrome
Error: Failed to execute 'querySelectorAll' on 'Element': '[ng:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak, .ng-hide:not(.ng-animate)' is not a valid selector.

in FF getting this error
[Exception... "The operation is insecure."  code: "18" nsresult: "0x80530012 (SecurityError)"  location: "<unknown>"]
http://localhost:8000/bower_components/angular/angular.js
Line 9383

**Comment by lebolo** [comment]
_Disclaimer: I'm not an active saveSvgAsPng developer, just a user ;)_

One possible solution would be to catch the exception and skip that CSS rule. So in `saveSvgAsPng.js` (currently @ line 46) change

``` javascript
var elems = dom.querySelectorAll(rule.selectorText);
if (elems.length > 0) {
  used += rule.selectorText + " { " + rule.style.cssText + " }\n";
}
```

to

``` javascript
try {
  var elems = dom.querySelectorAll(rule.selectorText);
  if (elems.length > 0) {
    used += rule.selectorText + " { " + rule.style.cssText + " }\n";
  }
} catch(e) {
  //console.error(e);
  continue;
} 
```

However, this means that any invalid CSS rules obviously won't be applied to the SVG that will ultimately become your PNG.

One may want to log the `SyntaxError` exception upon catching (or try to remove AngularJS specific rules?).

**Comment by exupero** [comment]
The code in question is filtering out unused CSS rules. I don't think there's a strong reason to do this, so I've removed it, which removes the usage of `Element.querySelectorAll` that errors when namespaced attribute names are part of the CSS selector.

**Comment by exupero** [comment]
This issue has resurfaced since I've re-added CSS rule filtering.

Unfortunately, I haven't been able to reproduce this error. I've added a CSS rule using the problem selector, but it appears invalid selectors like `[ng:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak, .ng-hide:not(.ng-animate)` are omitted from `cssRules`.

I'd appreciate any tips on how to see this error for myself.

**Comment by exupero** [comment]
6dc272f545f9c27baf2f9ba09a73fb1474b8af4d adds handling for invalid selector errors.

**Comment by ShadSterling** [comment]
I'm seeing a similar error

> Invalid CSS selector "svg:svg" DOMException: Failed to execute 'querySelector' on 'Element': 'svg:svg' is not a valid selector.

at `saveSvgAsPng.js:68` on a rule in [`jquery.svg.package-1.5.0/jquery.svg.css`](https://github.com/kbwood/svg/blob/master/jquery.svg.css)

**Comment by exupero** [comment]
Make sure you're using the latest code. That error wouldn't be thrown on [line 68](https://github.com/exupero/saveSvgAsPng/blob/gh-pages/saveSvgAsPng.js#L68) of the latest version.

**Comment by Polyergic** [comment]
Update fixed it, thanks.

**Comment by ShadSterling** [comment]
I thought the update had fixed it, but apparently I just failed to see the message... now it occurs on [line 96](https://github.com/exupero/saveSvgAsPng/blob/gh-pages/saveSvgAsPng.js#L96), apparently while processing [this rule](https://github.com/kbwood/svg/blob/master/jquery.svg.css#L4).

**Comment by exupero** [comment]
I'm having trouble reproducing the error your describe. Can you supply an example failure via JSBin or JSFiddle?

**Comment by ShadSterling** [comment]
I've [attempted](https://jsbin.com/zacapa/edit?html,js,output) that (_JSBin will download an image when opened_), but I don't see the error there either.  It occurs in our app when trying to save an svg from within an iframe of a [wysihtml5](https://github.com/xing/wysihtml5) document to which we programmatically copy all stylesheets from the containing page.  It turns out we don't actually use the [jQuery SVG plugin](https://github.com/kbwood/svg) that has the stylesheet that triggers the error, so the solution for us is to just not load that stylesheet.
