### ISSUE TITLE
Some text is not being converted

### ISSUE THREAD

**Issue by jameskelleher** [exupero/saveSvgAsPng#12]
I'm attempting to use the function with a bar chart.  Everything converts perfectly except for both the text that labels the tick marks, and the text that labels the legend.

**Comment by lebolo** [comment]
I had this same issue. For me, the problem was that I was setting the CSS `font-size` parameter using a `body` tag. The code tries to import all relevant CSS starting from the SVG element you feed it, so any CSS not set directly on SVG elements or their children won't be imported.

The solution is to set your `font-size` using SVG elements, like

```
.axis text { font-size: 12px; }
.legend text { font-size: 12px; }
```

Make sense?

**Comment by jameskelleher** [comment]
Perfect.  Thanks for the quick turnaround, too.
