### ISSUE TITLE
Modify specific class

### ISSUE THREAD

**Issue by lindstrm** [exupero/saveSvgAsPng#152]
Is there a way to modify a specific class when saving?
I need to hide some buttons that doesn't need to be shown in the images :)

**Comment by exupero** [comment]
You can probably use the option `modifyStyle`. It takes a function that receives the text of a CSS rule, including the selector and styles, and returns a replacement.

**Comment by Julianoe** [comment]
I can't figure out how to use this option `modifyStyle` and the index does not contain any example :(
Could you provide a simple example of its use? That'd be great!

@lindstrm did you achieve to do it?

**Comment by exupero** [comment]
My apologies. I read the wrong docs for `cssText` rather than confirming manually. You are correct that the existing usage of `modifyStyle` does not pass the CSS selector.

I've added a new option, `modifyCss`, to which is passed both the CSS selector and the CSS properties, and expects that a string of valid CSS is returned. Here's an example:

https://github.com/exupero/saveSvgAsPng/blob/31c8a527f72ee154b58c6f36f401d08e4d104da5/index.html#L372-L376

I've published a new version (1.3.1) to NPM. Let me know if you have any other needs. Thanks!
