### ISSUE TITLE
Possible to use with webpack / require?

### ISSUE THREAD

**Issue by ct14it** [exupero/saveSvgAsPng#160]
First off, when I reference the saveSvgAsPng.js library directly  via a `script src=` tag everything works great, so thanks for that.

I'm developing a Laravel app and I'm wondering if I can use this library via a webpack / require command? Something like....

`require('save-svg-as-png/saveSvgAsPng.js');`

Webpack compiles it no problem but I get told `saveSvgAsPng` is undefined if I try to reference it.

When I look at the compiled JS file, I see the source of saveSvgAsPng is there, but it doesn't appear to be exposing it.

I know this isn't strictly an issue with this library but any pointers would be great.

**Comment by exupero** [comment]
Webpack indicates that it works with AMD modules, which this library should be available as, as it calls `define` with a factory function. It's possible something is amiss here. Try fiddling with the following code (maybe just return `$out` rather than a function?) and see if it it helps with Webpack. If you figure something out, I'd be happy to consider a pull request.

https://github.com/exupero/saveSvgAsPng/blob/115bf91a7eca18cfbe7bc0202c0d02ec7d2b647d/saveSvgAsPng.js#L496-L501

**Comment by ct14it** [comment]
Cheers for the quick response @exupero I'll have a look and let you know when/if I figure anything out!

**Comment by petterw03** [comment]
I had the same problem, but solved it by first importing it

`import saveSvgAsPng from 'save-svg-as-png';`

and then, curiously, I had to use the following call to use it:

`saveSvgAsPng.saveSvgAsPng(svg, "file.png");`

**Comment by exupero** [comment]
The `saveSvgAsPng` function isn't exported as the default export. To use it without qualifying the name, you need to import as

```js
import {saveSvgAsPng} from 'save-svg-as-png';
```

**Comment by ct14it** [comment]
Nice one thanks for the solutions!
