### ISSUE TITLE
Error when saving svg as png

### ISSUE THREAD

**Issue by vdelacruz01** [exupero/saveSvgAsPng#18]
Good day! This is regards to saveSvgAsPng program that you made. I have some few questions. First, when I am trying your demo, I can't save a svg file as png and an error has been log to the console saying that "Uncaught SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported. saveSvgAsPng.js:34img.onload".

Another, as you said, to make the program work I must add `saveSvgAsPng(document.getElementById("diagram"), "diagram.png", 3);`
What does the following means? Is a diagram id is a div? And why is there a diagram.png? What is the purpose of the file? Hoping for your response, thank you!

**Comment by exupero** [comment]
What browser are you using? `toDataURL` is known to throw a SecurityError in IE.

The first argument of `saveSvgAsPng` should be an SVG element, so you should give `document.getElementId` the ID on an SVG tag.

The file name (diagram.png, in the example case) is the default filename the PNG should be saved to.

**Comment by zoom2ashish** [comment]
Is there any plan to fix this "toDataURL" related issue for IE? Can we have alternate approach for IE?

**Comment by exupero** [comment]
You can try [canvg](https://github.com/gabelerner/canvg), which parses SVG code and draws it to a canvas rather than loading the SVG directly as an image.

For more information about the problem, see [this Stack Overflow question](http://stackoverflow.com/questions/21829799/security-err-dom-exception-18-when-invoking-todataurl-method-of-the-canvas).
