### ISSUE TITLE
Issue when saving svg generated from mermaid

### ISSUE THREAD

**Issue by grofit** [exupero/saveSvgAsPng#88]
Hey,

I am trying to convert some svg diagrams created from mermaid into pngs but I just keep getting an error which doesnt tell me too much:

`There was an error loading the data URI as an image`

There is an event attached but there isn't much info on what the actual error is on there, I tried debugging but I don't know where the actual error is raised from and the data uri that is being applied seems ok from what I can tell.

**Comment by exupero** [comment]
The specific error should be logged after that message (see [this line](https://github.com/exupero/saveSvgAsPng/blob/gh-pages/saveSvgAsPng.js#L235)).

**Comment by grofit** [comment]
As mentioned that object which comes with the message is some sort of event object which just contains a lot of information but none of it is an error and the only thing of note in there is the image element reference. I can provide a screenshot if that would help?

**Comment by exupero** [comment]
A screenshot might help, but a JSFiddle or JSBin that replicates the problem would be better.

**Comment by grofit** [comment]
Will see if I can isolate it for you but while you wait here is the output (the path contains the img element):

![error output](https://dl.dropboxusercontent.com/u/98595151/ShareX/EMBERSOFT1/16/05/electron_2016-05-19_07-54-03.png)

The only quirks I can think of in this scenario are that I basically do a deep copy of the DOM using `cloneNode(true)` then work off that for the images etc, so I know other canvas based libs sometimes flip out if the elements you are working with are not actually part of the document or in the page, but are in memory.

**Comment by grofit** [comment]
Hey,

Here is a reproduction, not entirely sure why it happens as the firstChild seems to be the correct svg (if you console.log it).

http://codepen.io/grofit/pen/KzjVvy?editors=1010

I will have a play to see if I can find a workaround.

**Comment by exupero** [comment]
@grofit Try the latest and let me know whether it works for you.

**Comment by grofit** [comment]
Running latest version and then outputting the output into a new tab and running it gives me the error:

```
This page contains the following errors:

error on line 33 at column 405: Attribute xmlns redefined
Below is a rendering of the page up to the first error.
```

**Comment by exupero** [comment]
I was hoping that's what the latest version fixed. I don't know how Mermaid is setting the xmlns attribute, but [here's the line](https://github.com/exupero/saveSvgAsPng/blob/19ebb3acc316b611985abac79eb5b79c887c15d3/saveSvgAsPng.js#L185) that needs to be tweaked to detect whether there's already an xmlns attribute.

**Comment by jacoscaz** [comment]
Same here! I'm using vanilla Chrome and an SVG generated from Chartist.js.

**Comment by jacoscaz** [comment]
@exupero manually replacing all instances of `xmlns="http://www.w3.org/2000/xmlns/"`with an empty string solves the issue in my case.

**Comment by exupero** [comment]
I'm open to a pull request that provides a better solution to setting the `xmlns` attribute on foreignObject children.

**Comment by jacoscaz** [comment]
@exupero I'd be happy to contribute but this is not familiar territory. I can look into this over the weekend. Any pointers to relevant / useful documentation?

**Comment by exupero** [comment]
The problem is with the children of `foreignObject` elements. The top-most children need to have the `xmlns` attribute set back to the HTML XML namespace, rather than the SVG namespace. Originally, users had to specify the namespace themselves to get the children of foreignObject elements to show up in the rendered PNG, but not long ago I added [this code](https://github.com/exupero/saveSvgAsPng/blob/19ebb3acc316b611985abac79eb5b79c887c15d3/saveSvgAsPng.js#L183-L188) to add the HTML namespace automatically.

I have two tests of this code on the [test page](http://exupero.org/saveSvgAsPng/) (see the "foreign object" examples). One omits the `xmlns` attribute for the foreignObject child; the other includes the `xmlns` attribute manually in the HTML. Both work.

Mermaid and Chartist appear to also be adding an `xmlns` attribute as well, probably for the same reason this library is. The problem is that they seem to be doing it some way that `Element.getAttributeNS('xml', 'xmlns')` doesn't find.

Solving the double `xmlns` attribute problem should be as simple as figuring out how to robustly detect an `xmlns` attribute that has already been set.

**Comment by grofit** [comment]
Sorry guys I have been assigned onto something else recently but will be back on this soon, it seems like you both are onto a solution so thanks for finding the root cause.
