### ISSUE TITLE
Multiple SVG's

### ISSUE THREAD

**Issue by mrbormeth** [exupero/saveSvgAsPng#98]
Hey m8 :)
I've managed to use saveSvgAsPng which works like a charm!

Is it possible to add more SVG's and them have them placed side by side?
I have 4 SVG's on my site that i would love to combine into 1 PNG.

**Comment by exupero** [comment]
You could probably get URIs for each image, then write them to different positions on a new canvas and download that. You'd likely have to expose the `download` function to call it directly.

Alternatively, you may be able to create an SVG that references other SVGs on the page by ID in order to get them in a single image. I don't believe saveSvgAsPng has support for downloading such images. I think there's a pre-existing issue to that effect.

**Comment by mrbormeth** [comment]
Thanks for the answer. 
I think i'll go for the basic approach and just spawn 1 download dialog pr. SVG. 

Again thanks for this lib, saves me a lot of time.
